name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-16.04
    steps:
    - name: Check out repository.
      uses: actions/checkout@v2
    - name: Install build dependencies.
      run: sudo apt-get install gcc-m68k-linux-gnu python-pil
    - name: Build library and applets.
      run: make CROSS_COMPILE=m68k-linux-gnu- all
    - name: Upload artifacts.
      uses: actions/upload-artifact@v2
      with:
        name: betawise-applets
        path: "**/*.OS3KApp"
