name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-16.04
    steps:
    - name: Check out repository.
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install build dependencies.
      run: sudo apt-get install gcc-m68k-linux-gnu python-pil
    - name: Build library and applets.
      run: make CROSS_COMPILE=m68k-linux-gnu- all
    - name: Get the tag name.
      id: get_tag
      run: echo ::set-output name=TAG::$(git describe --tags | tail -c +2)
    - name: Upload artifacts.
      uses: actions/upload-artifact@v2
      with:
        name: betawise-applets-${{ steps.get_tag.outputs.TAG }}
        path: "**/*.OS3KApp"
