name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Install build dependencies.
      run: |
        sudo apt-get update
        sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
        sudo apt-get install python3-pil
    - name: Check out repository.
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build toolchain, library, and applets.
      run: |
        echo "$PREFIX/bin" >> $GITHUB_PATH
        make
    - name: Get the tag name.
      id: get_tag
      run: echo ::set-output name=TAG::$(git describe --tags | tail -c +2)
    - name: Upload applets artifact.
      uses: actions/upload-artifact@v2
      with:
        name: betawise-applets-${{ steps.get_tag.outputs.TAG }}
        path: "applets/**/*.OS3KApp"
    - name: Package toolchain.
      run: |
        ln -sf ${HOME}/.local /tmp/m68k-elf
        tar -C /tmp -cvhf m68k-elf-toolchain.tar m68k-elf
    - name: Upload toolchain artifact.
      uses: actions/upload-artifact@v2
      with:
        name: m68k-elf-toolchain-${{ steps.get_tag.outputs.TAG }}
        path: m68k-elf-toolchain.tar
